name: Check pre-commit hooks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install pre-commit
      - run: pre-commit run --all-files
