name: Run Core Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  core-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          # cache: 'pip' # Caching didn't make the CI faster and cache is quite big (4GB)

      - name: Install base dependencies
        run: pip install -e ".[test,gluonts,hfdataset]"

      - name: Run core tests
        run: pytest tests -s
