name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          # cache: 'pip' # Caching didn't make the CI faster and cache is quite big (4GB)

      - run: pip install -e ".[test,gluonts,hfdataset]"
      - run: pytest tests -s
